version: "3.9"

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py makemigrations habitat; python manage.py migrate; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db